#!/bin/bash

while true
do

    git status

    echo "Do you want to push all files? (y/n):"
    read push_all

    if [[ $push_all == "y" ]]; then

        git add .
        echo "Enter the commit message:"
        read message
        git commit -m "$message"
        git push
    else

        echo "Select the files you want to commit (space-separated):"
        read files


        git add $files

        echo "Enter the commit message:"
        read message

        git commit -m "$message"
        git push
    fi

    echo "________________"
    sleep 10
done
